log_format json_combined escape=json
'{'
  '"time":"$time_iso8601",'
  '"remote_addr":"$remote_addr",'
  '"method":"$request_method",'
  '"path":"$request_uri",'
  '"status":$status,'
  '"size":$body_bytes_sent,'
  '"referer":"$http_referer",'
  '"user_agent":"$http_user_agent",'
  '"request_time":$request_time'
'}';

server {
	listen 8080;
  access_log /dev/stdout json_combined;
  server_name reliableweb.dev;

  return 301 https://www.newline.co/courses/reliable-webservers-with-go;
}
